-- ============================================================================
-- Supabase Storage — session recording videos (LiveKit Egress destination)
-- Run AFTER schema.sql in the Supabase SQL editor.
-- ============================================================================

-- Private bucket for MP4 recordings. LiveKit writes via the S3-compatible API;
-- members read via signed URLs generated by the server API.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'session-recordings',
  'session-recordings',
  false,
  524288000, -- 500 MB
  array['video/mp4']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Authenticated members can stream/download objects (signed URLs also work).
drop policy if exists session_recordings_storage_read on storage.objects;
create policy session_recordings_storage_read on storage.objects
  for select
  to authenticated
  using (bucket_id = 'session-recordings');

-- Admins can delete old recordings from the dashboard/tools if needed.
drop policy if exists session_recordings_storage_admin on storage.objects;
create policy session_recordings_storage_admin on storage.objects
  for all
  to authenticated
  using (bucket_id = 'session-recordings' and public.is_admin())
  with check (bucket_id = 'session-recordings' and public.is_admin());
